FROM ##from_image##
MAINTAINER mdye <mdye@us.ibm.com>

RUN mkdir -p /usr/local/synchrophasor/
ADD ./synchrophasor-dpe /usr/local/synchrophasor/
ADD ./VERSION /usr/local/synchrophasor/
ADD ./web /usr/local/synchrophasor/web

ENV "DPE_SERVE_PATH=/usr/local/synchrophasor"
EXPOSE 8080 9009

WORKDIR /usr/local/synchrophasor/
CMD ["./synchrophasor-dpe", "-v", "5", "-logtostderr"]
